// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnznxumbrnalgcnoogrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuem54dW1icm5hbGdjbm9vZ3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTIyNzgsImV4cCI6MjA3MjE4ODI3OH0.o9M2KuhuMgigLCYnBKFQo_1M_Qgej_ptVdHIst26OyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});